def print_full_page_info(page):
    print(f"Display title -> {page.displaytitle}")
    print('-----------')
    print(f"Title -> {page.title}")
    print('-----------')
    print(f"URL -> {page.fullurl}")
    print('-----------')
    print(f"Canonical URL -> {page.canonicalurl}")
    print('-----------')
    print(f"Sections -> {page.sections}")
    print('-----------')
    print(f"Summary -> {page.summary}")
    print('-----------')
    print(f"Language -> {page.language}")
    print('-----------')
    print(f"Categories -> {page.categories}")
    print('-----------')
    print(f"Namespace -> {page.namespace}")
    print('-----------')
    print(f"Backlinks -> {page.backlinks}")
    print('-----------')
    print(f"Links -> {page.links}")
    print('-----------')
    print(f"Text -> {page.value}")
    print('-----------')
    print(f"Lang links -> {page.langlinks}")



